[package]
name = "kzg-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", optional = true, default-features = false, features = [
    "alloc",
    "derive",
] }
glob = "0.3.1"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
serde_derive = "1.0"
serde_yaml = { version = "0.9" }
sp1-derive = { git = "https://github.com/succinctlabs/sp1.git", branch = "main" }
once_cell = "1.19.0"
bls12_381 = { git = "https://github.com/0xWOLAND/bls12_381" }
regex = "1.10.5"
subtle = "2.2.1"
serde_json = "1.0.117"
const-chunks = "0.3.0"

[features]
default = ["std"]
serde = ["dep:serde"]
std = ["hex/std", "serde/std"]
cache = []

[[bin]]
name = "build_binaries"
path = "scripts/build_binaries.rs"
